name: Scrape Smartphone Data, Build the Model and upload it

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v4.1.1

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.11'
          cache: 'pip'
          
      - name: install python packages
        run: pip install -r requirements.txt
          
      - name: scrape Smartphone data
        working-directory: ./spider/spider/spiders
        run: python getSmartphoneData.py

      - name: upload data to mongodb 
        working-directory: spider/downloads
        run: python ./mongo_import.py -u "${{secrets.MONGODB_URI}}" -i '/Users/morenogallo/Desktop/ZHAW/6_Semester/MDM/MDM_Projekt1_Moreno_Gallo/spider/spider/spiders/produkte.json' -d 'produkte' -c 'produkte'

      - name: build model
        working-directory: model 
        run: python ./model.py -u "${{secrets.MONGODB_URI}}"

      - name: upload model
        working-directory: model
        run: python ./save.py -c "${{secrets.AZURE_STORAGE_CONNECTION_STRING}}"
